/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.59
 * Generated at: 2015-07-27 17:36:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!-- Sprout Tech Desktop Version -->\n");
      out.write("<!-- Author: Rajesh BASNET -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("   \n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\t\n");
      out.write("\t<meta charset=\"UTF-8\">\n");
      out.write("\t<title>Document</title>\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/custom.css\" >\n");
      out.write(" \t<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js\"></script>\n");
      out.write("\t<link href='http://fonts.googleapis.com/css?family=Vollkorn' rel='stylesheet' type='text/css'>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- js -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<script src=\"javaScript/classie.js\"></script>\n");
      out.write("\t<script src=\"javaScript/myjs.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- End of Js -->\n");
      out.write("\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<div class=\"container-fluid\">\n");
      out.write("\t\t\n");
      out.write("\n");
      out.write("\t\t<!-- Header Section -->\n");
      out.write("\t\t<header class =\"row \" >\n");
      out.write("\t\t\t<div id=\"logo\"></div>\n");
      out.write("\t\t\t\t<div class=\"menu\">\n");
      out.write("\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\"><button class=\"btn btn-default\" id=\"menuBtn\">Portfolio</button></a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"team\"><button class=\"btn btn-default\" id=\"menuBtn\">Team Sprout</button></a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\"><button class=\"btn btn-default\" id=\"menuBtn\">Contact</button></a></li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t</header>\n");
      out.write("\n");
      out.write("\t\t\n");
      out.write("\t\t<!-- Lnding page background -->\n");
      out.write("\t\t<div  class=\"row\">\n");
      out.write("\t\t\t<div id=\"introImage\">\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\n");
      out.write("\t\t<!-- Feature Section -->\n");
      out.write("\t\t<div class=\" row featureWrapper\">\n");
      out.write("\t\n");
      out.write("\t\t\t<div class=\"col-md-4 col-sm-12\" id=\"feature\">\n");
      out.write("\t\t\t\t<img src= \"images/ebay.png\">\n");
      out.write("\t\t\t\t<div> \n");
      out.write("\t\t\t\t\tIf you are not on the web, you are missing one of the most powerful tool\n");
      out.write("\t\t\t\t\tof marketing. The trend of getting information has been changed over time.\n");
      out.write("\t\t\t\t\tWe can make your presence on the web with eyecatching websites with web and mobile technology\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"col-md-4 col-sm-12\" id=\"feature\">\n");
      out.write("\t\t\t\t<img src = \"images//facebook.png\">\n");
      out.write("\t\t\t\t<div>\n");
      out.write("\t\t\t\t\tOur design presents your norms and values to deliver real yourself to your customers.\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"col-md-4 col-sm-12\" id=\"feature\">\n");
      out.write("\t\t\t\t<img src=\"images/email.png\">\n");
      out.write("\t\t\t\t<div>\n");
      out.write("\t\t\t\t\tThis is a sample application demonstrating how to build a CRUD application with Angular.js and RESTful services.\n");
      out.write("\n");
      out.write("\t\t\t\t\tSelect a wine in the list on the left ro edit the details, or click the New Wine button to add a wine to your Wine Cellar.\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\t\n");
      out.write("\n");
      out.write("\t\t<!-- Footer Section -->\n");
      out.write("\t\t<div class=\"row\">\n");
      out.write("\n");
      out.write("\t\t\t<footer class=\"footer\">\n");
      out.write("\t\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- About us-->\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"col-md-4\">\n");
      out.write("\t\t\t\t\t<ul id=\"footerAboutServices\" style=\"text-align:left;\">\n");
      out.write("\t\t\t\t\t\t<li><span style=\"font-size:18pt; font-weight:bold;\">About Sprout</span>\n");
      out.write("\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t<li>This is a sample application demonstrating how to build a CRUD application with Angular.js and RESTful services.\n");
      out.write("\t\t\t\t\t\t\tSelect a wine in the list on the left ro edit the details, or click the New Wine button to add a wine to your Wine Cellar.If you are not on the web, you are missing one of the most powerful tool of marketing. The trend of getting information has been changed over time. We can \n");
      out.write("\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- Services -->\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"col-md-4\">\n");
      out.write("\t\t\t\t\t<ul id=\"footerAboutServices\" style=\"text-align:left; \">\n");
      out.write("\t\t\t\t\t\t<li><span style=\"font-size:18pt; font-weight:bold;\">Services</span>\n");
      out.write("\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t<li style=\"border-bottom:1px solid grey;\">Web Design</li>\n");
      out.write("\t\t\t\t\t\t<li style=\"border-bottom:1px solid grey;\">Web Development</li>\n");
      out.write("\t\t\t\t\t\t<li style=\"border-bottom:1px solid grey;\">Application Development</li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\n");
      out.write("\t\t\t\t<!--Contacts-->\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"col-md-4\" >\n");
      out.write("\t\t\t\t\t<ul id=\"footerList\">\n");
      out.write("\t\t\t\t\t\t<li><img id=\"footerLogo\" src=\"images/sprout.png\"></li>\n");
      out.write("\t\t\t\t\t\t<li style=\"color:white;\">\n");
      out.write("\t\t\t\t\t\t\tSydney, NSW 2220<br />\n");
      out.write("\t\t\t\t\t\t\tPhone: 0433371679<br />\n");
      out.write("\t\t\t\t\t\t\tFax: 631-270-1502<br />\n");
      out.write("\t\t\t\t\t\t\tEmail:info@sprouttech.com.au\n");
      out.write("\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t</footer>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<!-- Copy Rights Section -->\n");
      out.write("\t\t\n");
      out.write("\t\t<div class=\"row cr-section\">\n");
      out.write("\n");
      out.write("\t\t\t<ul id=\"copyrights\"><li>Copyright 2015 <span style=\"color:#f16521;font-weight:bold;\">Sprout</span>Tech | All Rights Reserved | Privacy Policy | Terms and Conditions</li></ul>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- Js -->\n");
      out.write("\n");
      out.write("\t<script src=\"javaScript/bootstrap.min.js\"></script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
