/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.59
 * Generated at: 2015-07-28 05:07:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class team_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Our Team</title>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- Bootstrap -->\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.min.css\" />\n");
      out.write("<link rel=\"stylesheet\" href=\"css/custom.css\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("\thref=\"fontIcons/css/font-awesome.min.css\">\n");
      out.write("\n");
      out.write("<!-- Web fonts -->\n");
      out.write("<link href='http://fonts.googleapis.com/css?family=Vollkorn'\n");
      out.write("\trel='stylesheet' type='text/css'>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- JavaScript & JQuery -->\n");
      out.write("<script\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- Bootstrap JQuery -->\n");
      out.write("<script src=\"js/bootstrap.min.js\"></script>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<div class=\"container-fluid\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t<header class=\"row \">\n");
      out.write("\n");
      out.write("\t\t\t<div id=\"logo\"></div>\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"menu\">\n");
      out.write("\n");
      out.write("\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t<li><a href=\"home\"><i class=\"fa fa-home fa-lg homeIcon\"></i></a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"portfolio\"><button class=\"btn btn-default \" id=\"menuBtn\" >Portfolio</button></a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"team\"><button class=\"btn btn-default \" id=\"menuBtn\"  style=\"border:1px white solid;\">Team Sprout</button></a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"contact\"><button class=\"btn btn-default\" id=\"menuBtn\" >Contact</button></a></li>\n");
      out.write("\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t</header>\n");
      out.write("\t\t<!-- End of Header -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t<!--Main Body Section -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t<div class=\"row profileSection\">\n");
      out.write("\n");
      out.write("\t\t\t<!-- right empty section -->\n");
      out.write("\t\t\t<div class=\"col-md-2\"></div>\n");
      out.write("\n");
      out.write("\t\t\t<!--profile container-->\n");
      out.write("\t\t\t<div class=\" col-md-8\">\n");
      out.write("\t\t\t\t<div class=\"profileContainer\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t<!-- profile image holder-->\n");
      out.write("\t\t\t\t\t<div class=\"profileImage\">\n");
      out.write("\t\t\t\t\t\t<img src=\"images/img.jpeg\">\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<!-- profile summary -->\n");
      out.write("\t\t\t\t\t<div class=\"profile\">\n");
      out.write("\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t<li id=\"name\">Rajesh Basnet</li>\n");
      out.write("\t\t\t\t\t\t\t<li id=\"title\">FOUNDER</li>\n");
      out.write("\t\t\t\t\t\t\t<li id=\"summary\">In todayâs ever-challenging job market,\n");
      out.write("\t\t\t\t\t\t\t\tjob seekers must be on the hunt for new opportunities 24/7 to\n");
      out.write("\t\t\t\t\t\t\t\tmaintain a competitive advantage over other top job\n");
      out.write("\t\t\t\t\t\t\t\tcandidates.But to do so successfully, job seekers must have\n");
      out.write("\t\t\t\t\t\t\t\tconstant access, both at home and on the go, to their social and\n");
      out.write("\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t<li><button class=\"btn btn-primary btn-lg emailMe\">SEND\n");
      out.write("\t\t\t\t\t\t\t\t\tME AN EMAIL</button></li>\n");
      out.write("\t\t\t\t\t\t\t<li><ul class=\"socialIcon\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><i class=\"fa fa-linkedin-square fa-3x sc\"></i></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><i class=\"fa fa-twitter-square fa-3x sc\"></i></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><i class=\"fa fa-github-square fa-3x sc\"></i></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><i class=\"fa fa-google-plus-square fa-3x sc\"></i></li>\n");
      out.write("\t\t\t\t\t\t\t\t</ul></li>\n");
      out.write("\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"profileContainer\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t<!-- profile image holder-->\n");
      out.write("\t\t\t\t\t<div class=\"profileImage\">\n");
      out.write("\t\t\t\t\t\t<img src=\"images/img.jpeg\">\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<!-- profile summary -->\n");
      out.write("\t\t\t\t\t<div class=\"profile\">\n");
      out.write("\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t<li id=\"name\">Rajesh Basnet</li>\n");
      out.write("\t\t\t\t\t\t\t<li id=\"title\">DESIGNER</li>\n");
      out.write("\t\t\t\t\t\t\t<li id=\"summary\">In todayâs ever-challenging job market,\n");
      out.write("\t\t\t\t\t\t\t\tjob seekers must be on the hunt for new opportunities 24/7 to\n");
      out.write("\t\t\t\t\t\t\t\tmaintain a competitive advantage over other top job\n");
      out.write("\t\t\t\t\t\t\t\tcandidates.But to do so successfully, job seekers must have\n");
      out.write("\t\t\t\t\t\t\t\tconstant access, both at home and on the go, to their social and\n");
      out.write("\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t<li><button class=\"btn btn-primary btn-lg emailMe\">SEND\n");
      out.write("\t\t\t\t\t\t\t\t\tME AN EMAIL</button></li>\n");
      out.write("\t\t\t\t\t\t\t<li><ul class=\"socialIcon\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><i class=\"fa fa-linkedin-square fa-3x sc\"></i></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><i class=\"fa fa-twitter-square fa-3x sc\"></i></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><i class=\"fa fa-github-square fa-3x sc\"></i></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><i class=\"fa fa-google-plus-square fa-3x sc\"></i></li>\n");
      out.write("\t\t\t\t\t\t\t\t</ul></li>\n");
      out.write("\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"profileContainer\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t<!-- profile image holder-->\n");
      out.write("\t\t\t\t\t<div class=\"profileImage\">\n");
      out.write("\t\t\t\t\t\t<img src=\"images/img.jpeg\">\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<!-- profile summary -->\n");
      out.write("\t\t\t\t\t<div class=\"profile\">\n");
      out.write("\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t<li id=\"name\">Rajesh Basnet</li>\n");
      out.write("\t\t\t\t\t\t\t<li id=\"title\">DEVELOPER</li>\n");
      out.write("\t\t\t\t\t\t\t<li id=\"summary\">In todayâs ever-challenging job market,\n");
      out.write("\t\t\t\t\t\t\t\tjob seekers must be on the hunt for new opportunities 24/7 to\n");
      out.write("\t\t\t\t\t\t\t\tmaintain a competitive advantage over other top job\n");
      out.write("\t\t\t\t\t\t\t\tcandidates.But to do so successfully, job seekers must have\n");
      out.write("\t\t\t\t\t\t\t\tconstant access, both at home and on the go, to their social and\n");
      out.write("\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t<li><button class=\"btn btn-primary btn-lg emailMe\">SEND\n");
      out.write("\t\t\t\t\t\t\t\t\tME AN EMAIL</button></li>\n");
      out.write("\t\t\t\t\t\t\t<li><ul class=\"socialIcon\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><i class=\"fa fa-linkedin-square fa-3x sc\"></i></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><i class=\"fa fa-twitter-square fa-3x sc\"></i></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><i class=\"fa fa-github-square fa-3x sc\"></i></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><i class=\"fa fa-google-plus-square fa-3x sc\"></i></li>\n");
      out.write("\t\t\t\t\t\t\t\t</ul></li>\n");
      out.write("\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t<!-- Left empty section -->\n");
      out.write("\t\t\t<div class=\"col-md-2\"></div>\n");
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\n");
      out.write("\t\t<!-- Made in Australia Section -->\n");
      out.write("\n");
      out.write("\t\t<div class=\"madeInAus\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!-- Footer Section -->\n");
      out.write("\t\t<div class=\"row\">\n");
      out.write("\n");
      out.write("\t\t\t<footer class=\"footer\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- About us-->\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"col-md-4\">\n");
      out.write("\t\t\t\t\t<ul id=\"footerAboutServices\" style=\"text-align: left;\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<li><span style=\"font-size: 18pt; font-weight: bold;\">About\n");
      out.write("\t\t\t\t\t\t\t\tSprout</span></li>\n");
      out.write("\t\t\t\t\t\t<li>This is a sample application demonstrating how to build a\n");
      out.write("\t\t\t\t\t\t\tCRUD application with Angular.js and RESTful services. Select a\n");
      out.write("\t\t\t\t\t\t\twine in the list on the left ro edit the details, or click the\n");
      out.write("\t\t\t\t\t\t\tNew Wine button to add a wine to your Wine Cellar.If you are not\n");
      out.write("\t\t\t\t\t\t\ton the web, you are missing one of the most powerful tool of\n");
      out.write("\t\t\t\t\t\t\tmarketing. The trend of getting information has been changed over\n");
      out.write("\t\t\t\t\t\t\ttime. We can</li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- Services -->\n");
      out.write("\t\t\t\t<div class=\"col-md-4\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t<ul id=\"footerAboutServices\" style=\"text-align: left;\">\n");
      out.write("\t\t\t\t\t\t<li><span style=\"font-size: 18pt; font-weight: bold;\">Services</span></li>\n");
      out.write("\t\t\t\t\t\t<li style=\"border-bottom: 1px solid grey;\">Web Design</li>\n");
      out.write("\t\t\t\t\t\t<li style=\"border-bottom: 1px solid grey;\">Web Development</li>\n");
      out.write("\t\t\t\t\t\t<li style=\"border-bottom: 1px solid grey;\">Application\n");
      out.write("\t\t\t\t\t\t\tDevelopment</li>\n");
      out.write("\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t<!--Contacts-->\n");
      out.write("\t\t\t\t<div class=\"col-md-4\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t<ul id=\"footerList\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<li><img id=\"footerLogo\" src=\"images/sprout.png\"></li>\n");
      out.write("\t\t\t\t\t\t<li style=\"color: white;\">Sydney, NSW 2220<br /> Phone:\n");
      out.write("\t\t\t\t\t\t\t0433371679<br /> Fax: 631-270-1502<br />\n");
      out.write("\t\t\t\t\t\t\tEmail:info@sprouttech.com.au\n");
      out.write("\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</footer>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<!-- Copy Rights Section -->\n");
      out.write("\n");
      out.write("\t\t<div class=\"row cr-section\">\n");
      out.write("\n");
      out.write("\t\t\t<ul id=\"copyrights\">\n");
      out.write("\t\t\t\t<li>Copyright 2015 <span\n");
      out.write("\t\t\t\t\tstyle=\"color: #f16521; font-weight: bold;\">Sprout</span>Tech | All\n");
      out.write("\t\t\t\t\tRights Reserved | Privacy Policy | Terms and Conditions\n");
      out.write("\t\t\t\t</li>\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<script src=\"javaScript/classie.js\"></script>\n");
      out.write("\t<script src=\"javaScript/myjs.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
